# Import Libraries like MLPClassifier which is a neural network package provided python

In [126]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

# Import Dataset

In [110]:
data = pd.read_csv('/Users/aviratbelekar/Desktop/spring/ml/Assignment/iris.csv')

# Split into 80% training and 20% testing

In [112]:
X = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = data['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# Apply One-hot Encoding to Species column to convert categorical values to numeric values

In [113]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data["species"] = labelencoder.fit_transform(data["species"])
species = pd.DataFrame({'Species': ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']})

# Create dummies

In [114]:
def create_dummies(df,column_name):
    dummies = pd.get_dummies(df[column_name],prefix=column_name)
    df = pd.concat([df,dummies],axis=1)
    return df
data = create_dummies(data,"species")

# Convert data using Standard Scaler

In [127]:
unscaled_features = X_train 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_array = sc.fit_transform(X_train.values)
X_train = pd.DataFrame(X_train_array, index=X_train.index, columns=X_train.columns)
X_test_array = sc.transform(X_test.values)
X_test = pd.DataFrame(X_test_array, index=X_test.index, columns=X_test.columns)

# Implement MLP classifier using the following :
## Solver = sgd
## Activation Function = tanh
## Number of Layers = 1
## Number of hidden units = 30

In [128]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(30), max_iter=500,solver = 'sgd',activation = 'tanh')
mlp.fit(X_train, y_train.values.ravel())

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=30, learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

# Predictions using above Neural Network configurations

In [131]:
predictions = mlp.predict(X_test)

# Accuracy and Confusion Matrix

In [132]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predictions))
print(accuracy_score(predictions,y_test))

[[10  0  0]
 [ 0 10  2]
 [ 0  1  7]]
0.9


# Implement MLP classifier using the following :
## Solver = sgd
## Activation Function = relu
## Number of Layers = 2
## Number of hidden units = 30

In [119]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(30,30), max_iter=500,solver = 'sgd',activation = 'relu')
mlp.fit(X_train, y_train.values.ravel())

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(30, 30), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

# Predictions using above Neural Network configurations

In [120]:
predictions = mlp.predict(X_test)

# Accuracy and Confusion Matrix

In [121]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predictions))
print(accuracy_score(predictions,y_test))

[[ 9  1  0]
 [ 0 10  2]
 [ 0  0  8]]
0.9


# Implement MLP classifier using the following :
## Solver = sgd
## Activation Function = logistic
## Number of Layers = 3
## Number of hidden units = 30

In [123]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30), max_iter=500,solver = 'sgd',activation = 'logistic')
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(30, 30, 30), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

# Predictions using above Neural Network configurations

In [124]:
predictions = mlp.predict(X_test)

# Accuracy and Confusion Matrix

In [125]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predictions))
print(accuracy_score(predictions,y_test))

[[10  0  0]
 [12  0  0]
 [ 8  0  0]]
0.3333333333333333
